Perfomans/Models/Evaluations.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Perfomans.Models
{
    public class Evaluations
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public int? AssessorId { get; set; }
        public User Assessor { get; set; }

        public List<UserParamEval> UserParamEvals { get; set; }

        public Evaluations()
        {
            UserParamEvals = new List<UserParamEval>();
        }
    }
}

Perfomans/Controllers/EvaluationsController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perfomans.Models;
using Perfomans.Service;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;

namespace Perfomans.Controllers
{
    public class EvaluationsController : Controller
    {
        private readonly IEvalService _service;
        private readonly ApplicationContext _context;

        public EvaluationsController(IEvalService service, ApplicationContext context)
        {
            _service = service;
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_service.AllCorrentAssesorEvaluations(User.Identity.Name));
        }
        public IActionResult EvaluationPage(int? id)
        {
            ViewBag.Parameters = _service.AllParam();
            ViewBag.AllUsers = _service.MyEmployees(User.Identity.Name);
            var evaluation = _service.GetById(id);
            return View(evaluation);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Date,ParameterId,UserId,Mark")] Evaluations evaluations)
        {
            if (ModelState.IsValid)
            {
                evaluations.AssessorId = _service.GetCorrentAssesor(User.Identity.Name);
                _context.Evaluations.Add(evaluations);
                _context.SaveChanges();
                _service.Insert(evaluations);
                return RedirectToAction("EvaluationMarksGrid", new { id = evaluations.Id });
            }

            return View(evaluations);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id,Date,ParameterId,UserId,Mark")] Evaluations evaluations, List<int> marks)
        {
            _service.Update(evaluations, marks);
            return RedirectToAction("EvaluationPage", new { id = evaluations.Id});
        }

        public IActionResult EvaluationMarksGrid(int? id)
        {
            ViewBag.Parameters = _service.AllParam();
            ViewBag.AllUsers = _service.MyEmployees(User.Identity.Name);
            var evaluation = _service.GetById(id);
            return View(evaluation);
        }

        public IActionResult Delete(int? id)
        {
            var evaluation = _service.GetById(id); 
            return View(evaluation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult Import(IFormFile file, int? id)
        {
           List<UserParamEval> upelist = _context.UserParamEval.Where(upe=> upe.EvaluationsId == id).ToList();
            using (var stream = new MemoryStream())
            {
                file.CopyToAsync(stream);
                using (var package = new ExcelPackage(stream))
                {
                    ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
                    var rowcount = worksheet.Dimension.Rows;
                    var colscount = worksheet.Dimension.Columns;
                    for(int row = 2; row<= rowcount; row++)
                    {
                        for(int coll = 2; coll<= colscount; coll++)
                        {
                           foreach(UserParamEval paramEval in upelist)
                            {
                             paramEval.Mark = Convert.ToInt32(worksheet.Cells[row,coll].Value.ToString().Trim());

                            }
                        }
                    }
                } 
            }
            _context.SaveChanges();
            return RedirectToAction("EvaluationPage", new { id= id});
        }

    }
}

Perfomans/Views/Evaluations/Create.cshtml
@model Perfomans.Models.Evaluations

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Evaluations</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Perfomans/Views/Evaluations/Delete.cshtml
@model Perfomans.Models.Evaluations

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evaluations</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assessor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assessor.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Perfomans/Views/Evaluations/EvaluationMarksGrid.cshtml
@model Perfomans.Models.Evaluations

@{
    ViewData["Title"] = "Marks";
}


<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div style="margin-top:2em" class="container">
        <div class="row">
            <div class="col-sm">
                <div>
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Date)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Date)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Assessor)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Assessor.Name)
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="col-sm">
                <input type="submit" class="SecondaryB" style="float:right" value="Save">
                @using (Html.BeginForm("Import", "Evaluations", FormMethod.Post, new { enctype = "multipart/form-data", id = Model.Id }))
                {
                    <div>
                        <input type="file" name="fileExcel" id="fileExcel" />>
                        <button type="submit" class="SecondaryB">Import from Excel</button>
                    </div>
                }
            </div>
        </div>
    </div>

    <table style="margin-top:2em" class="table table-hover">
        <thead>
            <tr>
                <th scope="col"></th>

                @foreach (Parameters parameters in ViewBag.Parameters)
                {
                    <th scope="col">
                        <p style=" margin-top:3.5em;font-size: 12px;transform: rotate(-90deg);filter: flipH flipV;height: 40px; width:30px">
                            @parameters.Name
                        </p>
                    </th>
                }
            </tr>
        </thead>

        <tbody>
            @foreach (User user in ViewBag.AllUsers)
            {
                <tr>

                    <td>
                        @user.Name <span> </span> @user.SourName
                    </td>

                    @foreach (UserParamEval paramEval in Model.UserParamEvals.Where(pe => pe.UserId == user.Id))
                    {
                        <td>
                            <input style="width: 50%; margin-top: 20%; border-color: transparent; " type="text" name="marks" id="marks" value="@paramEval.Mark" />
                        </td>

                    }
                </tr>
            }
        </tbody>
    </table>

</form>
 

Perfomans/Views/Evaluations/EvaluationPage.cshtml
@model Perfomans.Models.Evaluations

@{
    ViewData["Title"] = "EvaluationPage";
}

<div style="margin-top:2em" class="container">
    <div class="row">
        <div class="col-sm">
            <div>
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Date)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Date)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Assessor)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Assessor.Name)
                    </dd>
                </dl>
            </div>
        </div>
        <div class="col-sm">
            <a class="SecondaryB" style="float:right" asp-action="EvaluationMarksGrid" asp-route-id="@Model.Id"><i class="pencil alternate icon"></i>Edit</a>

        </div>
    </div>
</div>
<table style="margin-top:2em" class="table table-hover">
    <thead>
        <tr>
            <th scope="col"></th>

            @foreach (Parameters parameters in ViewBag.Parameters)
            {
                <th scope="col">
                    <p style=" margin-top:3.5em;font-size: 12px;transform: rotate(-90deg);filter: flipH flipV;height: 40px; width:30px">
                        @parameters.Name
                    </p>
                </th>
            }
        </tr>
    </thead>
    <tbody>

        @foreach (User user in ViewBag.AllUsers)
        {
            <tr>
                <td>
                    @user.Name <span> </span> @user.SourName
                </td>
                @foreach (UserParamEval paramEval in Model.UserParamEvals.Where(pe => pe.UserId == user.Id))
                {
                    <td>
                        @paramEval.Mark
                    </td>
                }
            </tr>
        }

    </tbody>
</table>

Perfomans/Views/Evaluations/Index.cshtml
@model IEnumerable<Perfomans.Models.Evaluations>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assessor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Assessor.Name)
                    </td>
                    <td>
                        <a asp-action="EvaluationPage" asp-route-id="@item.Id">Show</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>

        }
    </tbody>
</table>