Perfomans/Models/Departments.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Perfomans.Models
{
    public class Departments
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is not specified")]
        public string Name { get; set; }
        public List<DepartmentParameters> DepartmentParameters { get; set; }
        public List<User> User { get; set; }
        public List<Groups> Groups { get; set; }
        public Departments()
        {
            User = new List<User>();
            Groups = new List<Groups>();
        }
    }
}

Perfomans/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList;
using Perfomans.Models;
using System.Web;
using ClosedXML.Excel;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Perfomans.Service;

namespace Perfomans.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IDepartmentsService _service;
        private readonly IGroupService _groupService;

        public DepartmentsController(IDepartmentsService service, IGroupService groupService)
        {
            _service = service;
            _groupService = groupService;
        }

        [Authorize(Roles = "admin")]

        public ActionResult Index()
        {
            return View(_service.AllDepartments());
        }
        public ActionResult DepartmentPage(int? id)
        {
            ViewBag.LastEvalId = _service.GetLastEvaluations().Id;
            ViewBag.Parameters = _groupService.AllParameters();
            ViewBag.ParametersGroups = _groupService.AllParametersGroups();
            ViewBag.UserParamEvaluations = _service.AllUPE();
            return View(_service.DepEmployeesProgreses(id));
        }

        public IActionResult Create()=> View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name")] Departments departments)
        {
            if (ModelState.IsValid)
            {
                _service.Insert(departments);
                return RedirectToAction(nameof(Index));
            }
            return View(departments);
        }

        public IActionResult Edit(int? id)=> View(_service.GetById(id));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name")] Departments departments)
        {
            if (ModelState.IsValid)
            {
                _service.Update(departments);
                return RedirectToAction(nameof(Index));
            }
            return View(departments);
        }

        public IActionResult Delete(int? id)=>View(_service.GetById(id));

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        public ActionResult EmployeePartial()=>PartialView();
        public ActionResult GroupsEmployee(int GroupId, int DepId)
        {        
            ViewBag.Group = _groupService.GetById(GroupId);
            return View(_service.GetById(DepId));
        }
        public ActionResult ParametersPartial()=> PartialView();
        public ActionResult GroupsPartial()=>PartialView();
        public ActionResult TopEmployees(int EmployeeCount, int GroupId, int DepId)
        {    
            ViewBag.ParametersGroup = _groupService.AllParametersGroups().Where(p => p.GroupId == GroupId).ToList();
            ViewBag.GroupId = GroupId;
            ViewBag.Parameters = _groupService.AllParameters();
            ViewBag.Evaluations = _service.GetLastEvaluations();
            Departments departments = _service.GetById(DepId);
            List<User> CountTop = _service.CountTop(DepId, GroupId, EmployeeCount);
            ViewBag.topsort = CountTop;
            return View(departments);
        }
        public IActionResult Excel()
        {
            ViewBag.Parameters = _groupService.AllParameters();
            using (var workbook = new XLWorkbook())
            {
                _service.WorkbookCreate(workbook);
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(
                    content,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Top_Emplyee.xlsx");
                }
            }
        }
        public ActionResult Progress(int DepId, int Direction)
        {
            if (Direction == 1) { ViewBag.Direction = 1;}
            else {ViewBag.Direction = 0;}
            Departments departments = _service.DepEmployeesProgreses(DepId);
            ViewBag.Parameters = _groupService.AllParameters();
            ViewBag.Evaluations = _service.GetLastEvaluations();
            return View(departments);
        }
    }
}

Perfomans/Controllers/GroupsController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Perfomans.Models;
using Perfomans.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Perfomans.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IGroupService _service;
        public GroupsController(IGroupService service)
        {
            _service = service;
        }
        public IActionResult Create(int DepId)
        {
            ViewBag.DepId = DepId;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name")] Groups groups, int DepId)
        {
            groups.DepartmentId = DepId;
            if (ModelState.IsValid)
            {
                _service.Insert(groups);
                return RedirectToAction("DepartmentPage", "Departments", new { id = DepId });
            }
            return View(groups);
        }

        public IActionResult Edit(int? id, int DepId)
        {
            ViewBag.DepId = DepId;
            ViewBag.Parameters = _service.AllParameters();
            var Parameters = _service.AllParameters();
            ViewBag.SelectedItems = Parameters.ToList().Where(i => i.ParametersGroups.Where(p => p.GroupId == id).Count() > 0 ? true : false).ToList();
            Groups groups = _service.GetById(id);
            groups.ParametersGroups = _service.AllParametersGroups();
            return View(groups);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Groups groups, int[] selectedItems, int DepId)
        {
            Groups editgroup = _service.Update(groups, selectedItems, DepId);
            return RedirectToAction("EditGroupsParam", new { id =editgroup.id, DepId= DepId});
        }
        public IActionResult EditGroupsParam(int? id, int DepId)
        {
            ViewBag.DepId = DepId;
            ViewBag.Parameters = _service.AllParameters();
            Groups groups = _service.GetById(id);
            groups.ParametersGroups = _service.AllParametersGroups();
            var Parameters = _service.AllParameters();
            ViewBag.SelectedItems = Parameters.ToList().Where(i => i.ParametersGroups.Where(p => p.GroupId == id).Count() > 0 ? true : false).ToList();
            return View(groups);
        }
        public IActionResult Delete(int? id, int DepId)
        {
            ViewBag.DepId = DepId;
            Groups groups = _service.GetById(id);
            return View(groups);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id, int DepId)
        {
            _service.Delete(id);
            return RedirectToAction("DepartmentPage","Departments", new { id = DepId}) ;
        }

        public IActionResult Excel(int DepId)
        {
            using (var workbook = new XLWorkbook())
            {
                _service.WorkbookCreate(workbook, DepId);
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File( content,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Groups.xlsx");
                }
            }
        }

    }
}

Perfomans/Views/Departments/Create.cshtml
@model Perfomans.Models.Departments

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Departments</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perfomans/Views/Departments/Delete.cshtml
@model Perfomans.Models.Departments

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Departments</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Perfomans/Views/Departments/DepartmentPage.cshtml
@model Perfomans.Models.Departments
@using Perfomans.Models
@{
    ViewData["Title"] = "DepartmentPage";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#Chatbutton").click(function () {
            $("#Chatbutton").addClass('active');
            $("#Newsbutton").removeClass('active');
            $("#Groupbutton").removeClass('active');
            $("#groups").css("display", "none");
            $("#news").css("display", "none");
            $("#chat").css("display", "block");
        })
        $("#Newsbutton").click(function () {
            $("#Newsbutton").addClass('active');
            $("#Chatbutton").removeClass('active');
            $("#Groupbutton").removeClass('active');
            $("#groups").css("display", "none");
            $("#chat").css("display", "none");
            $("#news").css("display", "block");
        })
        $("#Groupbutton").click(function () {
            $("#Groupbutton").addClass('active');
            $("#Chatbutton").removeClass('active');
            $("#Newsbutton").removeClass('active');
            $("#chat").css("display", "none");
            $("#news").css("display", "none");
            $("#groups").css("display", "block");
        })
    });
</script>
<body>

    <div style="margin-top: 2em" class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="ui card">
                    <div class="content">
                        <div class="ui placeholder">
                            <div class="ui header">
                                <div class="content">
                                    <h2 class="header">
                                        @Model.Name
                                    </h2>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sub content">
                        @foreach (User u in Model.User)
                        {
                            if ((u.DepartmentId == Model.Id) & (u.RoleId == 4))
                            {
                                <h3 class="ui center aligned sub header">Head of department : @u.Name</h3>

                            }
                        }
                    </div>

                    <div style="margin-left:5%" class="extra content">
                        <div class="ui  buttons">
                            <a style="color: #54354F" class="ui  button" asp-action="Edit" asp-route-id="@Model.Id"><i class="edit icon"></i>Edit</a> |
                            <a style="color: #54354F" class="ui  button" asp-action="Delete" asp-route-id="@Model.Id"><i class="trash alternate icon"></i>Delete</a> |
                        </div>
                    </div>
                </div>
                <div>
                    <a asp-action="Index"><i class="chevron left icon"></i>Back</a>
                </div>
            </div>

            <div class="col-sm-9">
                <div class="ui segment">
                    <br />
                    <div class="ui secondary pointing menu">
                        <a id="Chatbutton" class="active item">
                            Employee
                        </a>
                        <a id="Newsbutton" class=" item">
                            Parameters
                        </a>

                        <a id="Groupbutton" class="item">
                            Groups
                        </a>
                    </div>
                    <div id="chat"><partial name="EmployeePartial.cshtml" /></div>
                    <div id="news" style="display: none"><partial name="ParametersPartial.cshtml" /></div>
                    <div id="groups" style="display: none"><partial name="GroupsPartial.cshtml" /></div>
                </div>
            </div>
        </div>
    </div>
</body>

Perfomans/Views/Departments/Edit.cshtml
@model Perfomans.Models.Departments

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Departments</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Perfomans/Views/Departments/EmployeePartial.cshtml
@model Perfomans.Models.Departments
@using Perfomans.Models

<div style="margin-top:1.5em" class="container">
    <div class="row">
        <div class="col">
            @using (Html.BeginForm("Progress", "Departments", FormMethod.Get))
            {
                <input type="hidden" id="DepId" name="DepId" value="@Model.Id" />
                <input type="hidden" id="Direction" name="Direction" value="1" />
                <button type="submit" style="width:100%; display:inline" class="SecondaryB">
                    <i class="chevron up icon"></i>
                </button>
            }
        </div>
        <div class="col">

            @using (Html.BeginForm("Progress", "Departments", FormMethod.Get))
            {
                <input type="hidden" id="Direction" name="Direction" value="0" />
                <input type="hidden" id="DepId" name="DepId" value="@Model.Id" />
                <button style="width:100%; display:inline" type="submit" class="SecondaryB">
                    <i class="chevron down icon"></i>
                </button>
            }
        </div>
        <div class="col">

        </div>
    </div>
</div>

            <table class="ui compact celled table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Sourname</th>
                        <th>Perfomances</th>
                        <th>Progress</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (User user in Model.User)
                    {
                        if (user.DepartmentId == Model.Id)
                        {
                        <tr>
                            <td>
                                @user.Name
                            </td>
                            <td>
                                @user.SourName
                            </td>
                            <td>
                                @foreach (DepartmentParameters deparameters in Model.DepartmentParameters)

                                {
                                    foreach(UserParamEval userParamEval in ViewBag.UserParamEvaluations)
                                    {
                                        if((deparameters.ParameterId == userParamEval.ParameterId) & (userParamEval.UserId == user.Id) & (userParamEval.EvaluationsId == ViewBag.LastEvalId))
                                        {
                                            @userParamEval.Parameter.Name
                                                <span> -</span>
                                            @userParamEval.Mark
                                        }
                                    }
                                    <br />
                                }
                            </td>
                            <td>
                                @if (user.progress == -1)
                                {
                                    <i class="chevron down icon"></i>
                                }
                                @if (user.progress == 1)
                                {
                                    <i class="chevron up icon"></i>
                                }
                                @if (user.progress == 0)
                                {
                                    <i class="minus icon"></i>
                                }
                            </td>

                        </tr>
                        }
                    }

                </tbody>
            </table>

Perfomans/Views/Departments/GroupsEmployee.cshtml
@model Perfomans.Models.Departments
@using Perfomans.Models

<div class="row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-6">
        <div style="margin-top: 3em" class="ui segment">
            <div style="padding:1em" class="ui form">
                <h1 class="ui center aligned header">Explore employee for<br />" @ViewBag.Group.Name "</h1>

                @using (Html.BeginForm("TopEmployees", "Departments", FormMethod.Get))
                {
                    <input type="hidden" id="GroupId" name="GroupId" value="@ViewBag.Group.id" />
                    <input type="hidden" id="DepId" name="DepId" value="@Model.Id" />
                    <input type="number" style="margin-top: 1.4em; width: 40%; margin-left: 30%" placeholder="Employees count" name="EmployeeCount" id="EmployeeCount" />
                    <button type="submit" style="margin-top:2em; margin-left:40%" class="SecondaryB">Create list</button>
                }
            </div>
        </div>

    </div>
    <div class="col-sm-3">
    </div>

</div>

Perfomans/Views/Departments/GroupsPartial.cshtml
@model Perfomans.Models.Departments
@using Perfomans.Models

<h1>Groups</h1>

<table class="ui compact celled definition table">
    <thead>
        <tr>
            <th></th>
            <th>Parameter</th>
            <th>Actions</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (Groups groups in Model.Groups)
        {
            if (groups.DepartmentId == Model.Id)
            {
            <tr>
                <td>
                    @groups.Name
                </td>
                <td>
                    @foreach (ParametersGroup parametersGroup in ViewBag.ParametersGroups)
                    {
                        @if (parametersGroup.GroupId == groups.id)
                        {
                            @parametersGroup.Parameters.Name<span>-</span>
                            @parametersGroup.Mark
                            <br />

                        }
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Groups", new { id = groups.id, DepId = Model.Id }) |
                    @Html.ActionLink("Delete", "Delete", "Groups", new { id = groups.id, DepId = Model.Id })

                </td>
                <td>
                    @Html.ActionLink("Show", "GroupsEmployee", "Departments", new { GroupId = groups.id, DepId = Model.Id })

                </td>
            </tr>
            }
        }

    </tbody>
    <tfoot class="full-width">
        <tr>
            <th></th>
            <th colspan="4">
                <div class="ui right floated small">
                    @using (Html.BeginForm("Create", "Groups", FormMethod.Get))
                    {
                        <input type="hidden" Id="DepId" name="DepId" value="@Model.Id">
                        <button type="submit" class="SecondaryB" style="float:right"><i class="plus icon"></i>Create New</button>
                    }
                    @Html.ActionLink("Export to Excel", "Excel", "Groups", new { DepId = Model.Id })

                </div>

            </th>
        </tr>
    </tfoot>
</table>

Perfomans/Views/Departments/Index.cshtml
@model IEnumerable<Perfomans.Models.Departments>
    <div style="" margin-top: 2em;">
        <a class="SecondaryB" style="float:right" asp-action="Create"><i class="plus icon"></i>Create New</a>
    </div>
    <div style="margin-top: 2em;" class="centered ui link cards">

        @foreach (var item in Model)
        {
            <div class="card">
                <a asp-action="DepartmentPage" asp-route-id="@item.Id">
                    <div class="content">
                        <div class="ui placeholder">
                            <h2 class="ui centered header">
                                @item.Name
                            </h2>
                        </div>

                    </div>
                </a>
            </div>

        }
    </div>
    <br />

Perfomans/Views/Departments/ParametersPartial.cshtml
@model Perfomans.Models.Departments
@using Perfomans.Models
<h1>Parameters</h1>

<table class="ui compact celled definition table">
    <thead>
        <tr>
            <th></th>
            <th>Mark</th>
        </tr>
    </thead>
    <tbody>
        @foreach (DepartmentParameters deparameters in Model.DepartmentParameters)
        {
            if (deparameters.DepartmentId == Model.Id)
            {
            <tr>

                @foreach (Parameters parameters in ViewBag.Parameters)
                {
                    if (deparameters.ParameterId == parameters.Id)
                    {
                        <td>@parameters.Name</td>

                    }
                }
                <td> 
                    @deparameters.mark
                </td>
                <td>
                    @using (Html.BeginForm("Delete", "DepParam", FormMethod.Get))
                    {
                        <input type="hidden" id="DepartmentId" name="DepartmentId" value="@deparameters.DepartmentId" />
                        <input type="hidden" id="ParameterId" name="ParameterId" value="@deparameters.ParameterId" />
                       <button type="submit"  style="margin-left: 1em; color: #54354F; border: none; float: left"><i class="trash alternate icon"></i></button>
                    }
                    
                    @using (Html.BeginForm("Edit", "DepParam", FormMethod.Get))
                    {
                        <input type="hidden" id="DepartmentId" name="DepartmentId" value="@deparameters.DepartmentId" />
                        <input type="hidden" id="ParameterId" name="ParameterId" value="@deparameters.ParameterId" />
                       <button type="submit" style="margin-left:1em; color:#54354F; border: none"><i class="edit icon"></i></button>
                    }
                </td>
            </tr>
            }
        }

    </tbody>
        <tfoot class="full-width">
            <tr>
                <th></th>
                <th colspan="4">
                    <div class="ui right floated small">
                        @using (Html.BeginForm("Create", "DepParam", FormMethod.Get))
                        {
                            <input type="hidden" Id="depId" name="depId" value="@Model.Id">
                            <button type="submit" class="SecondaryB" style="float:right"><i class="plus icon"></i>Create New</button>
                        }
                    </div>

                </th>
            </tr>
        </tfoot>
</table>

Perfomans/Views/Departments/Progress.cshtml
<div style="margin-top: 2em" class="container">
    <div class="row">
        <div class="col-sm-10">
            <table class="ui compact celled table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Sourname</th>
                        <th>Perfomances</th>
                        <th>Progress</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (User user in Model.User)
                    {
                        if (ViewBag.Direction == 1)
                        {
                            if (user.progress == 1)
                            {
                                <tr>
                                    <td>
                                        @user.Name
                                    </td>
                                    <td>
                                        @user.SourName
                                    </td>
                                    <td>
                                        @*@foreach (DepartmentParameters deparameters in Model.DepartmentParameters)

                                        {
                                            @foreach (Evaluations evaluations in ViewBag.Evaluations)
                                            {
                                                if ((deparameters.ParameterId == evaluations.ParameterId) & (evaluations.UserId == user.Id))
                                                {
                                                    @evaluations.Parameter.Name <span>-</span> @evaluations.Mark

                                                }
                                            }
                                            <br />
                                        }*@
                                    </td>
                                    <td>
                                        <i class="chevron up icon"></i>

                                    </td>

                                </tr>
                            }
                        }
                        else
                        {
                            if (user.progress == -1)
                            {
                                <tr>
                                    <td>
                                        @user.Name
                                    </td>
                                    <td>
                                        @user.SourName
                                    </td>
                                    @*<td>
                                        @foreach (DepartmentParameters deparameters in Model.DepartmentParameters)

                                        {
                                            @foreach (Evaluations evaluations in ViewBag.Evaluations)
                                            {
                                                if ((deparameters.ParameterId == evaluations.ParameterId) & (evaluations.UserId == user.Id))
                                                {
                                                    @evaluations.Parameter.Name <span>-</span> @evaluations.Mark

                                                }
                                            }
                                            <br />
                                        }
                                    </td>*@
                                    <td>
                                        <i class="chevron down icon"></i>

                                    </td>

                                </tr>
                            }
                        }
                    }

                </tbody>
            </table>
        </div>
        <div class="col-sm-2">

        </div>
    </div>
</div>

Perfomans/Views/Departments/TopEmployees.cshtml
@model Perfomans.Models.Departments
@using Perfomans.Models


<table style="margin-top:2em" class="ui compact celled definition table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Sourname</th>
            <th>Perfomances</th>
            <th>Result</th>

        </tr>
    </thead>
    <tbody>

        @foreach (User user in ViewBag.topsort)
        {
            <tr>
                <td>
                    @user.Name
                </td>
                <td>
                    @user.SourName
                </td>
                <td>
                    @*@foreach (ParametersGroup parametersGroup in ViewBag.ParametersGroup)

                    {
                        @foreach (Evaluations evaluations in ViewBag.Evaluations)

                        {
                            if ((parametersGroup.GroupId == ViewBag.GroupId) & (parametersGroup.ParameterId == evaluations.ParameterId) & (evaluations.UserId == user.Id))
                            {
                                @evaluations.Parameter.Name <span>-</span> @evaluations.Mark
                                <br />

                            }
                        }
                    }*@
                </td>
                <td>
                    @if (user.result != 0)
                    {@user.result}

                </td>
            </tr>
        }

    </tbody>
</table> 
       @Html.ActionLink("Export data to excel", "Excel", "Departments")