Perfomans/Controllers/ChartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using Grpc.Core;
using System.Drawing.Printing;
using System.Drawing.Text;
using Perfomans.Models;

namespace Perfomans.Controllers
{
    public class ChartController : Controller
    {
        private readonly ApplicationContext _context;

        public ChartController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.AllUsers = _context.User.ToList();
            return View(_context.Departments.ToList());
        }
    }

}

Perfomans/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList;
using Perfomans.Models;
using System.Web;
using ClosedXML.Excel;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Perfomans.Service;

namespace Perfomans.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IDepartmentsService _service;
        private readonly IGroupService _groupService;

        public DepartmentsController(IDepartmentsService service, IGroupService groupService)
        {
            _service = service;
            _groupService = groupService;
        }

        [Authorize(Roles = "admin")]

        public ActionResult Index()
        {
            return View(_service.AllDepartments());
        }
        public ActionResult DepartmentPage(int? id)
        {
            ViewBag.LastEvalId = _service.GetLastEvaluations().Id;
            ViewBag.Parameters = _groupService.AllParameters();
            ViewBag.ParametersGroups = _groupService.AllParametersGroups();
            ViewBag.UserParamEvaluations = _service.AllUPE();
            return View(_service.DepEmployeesProgreses(id));
        }

        public IActionResult Create()=> View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name")] Departments departments)
        {
            if (ModelState.IsValid)
            {
                _service.Insert(departments);
                return RedirectToAction(nameof(Index));
            }
            return View(departments);
        }

        public IActionResult Edit(int? id)=> View(_service.GetById(id));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name")] Departments departments)
        {
            if (ModelState.IsValid)
            {
                _service.Update(departments);
                return RedirectToAction(nameof(Index));
            }
            return View(departments);
        }

        public IActionResult Delete(int? id)=>View(_service.GetById(id));

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        public ActionResult EmployeePartial()=>PartialView();
        public ActionResult GroupsEmployee(int GroupId, int DepId)
        {        
            ViewBag.Group = _groupService.GetById(GroupId);
            return View(_service.GetById(DepId));
        }
        public ActionResult ParametersPartial()=> PartialView();
        public ActionResult GroupsPartial()=>PartialView();
        public ActionResult TopEmployees(int EmployeeCount, int GroupId, int DepId)
        {    
            ViewBag.ParametersGroup = _groupService.AllParametersGroups().Where(p => p.GroupId == GroupId).ToList();
            ViewBag.GroupId = GroupId;
            ViewBag.Parameters = _groupService.AllParameters();
            ViewBag.Evaluations = _service.GetLastEvaluations();
            Departments departments = _service.GetById(DepId);
            List<User> CountTop = _service.CountTop(DepId, GroupId, EmployeeCount);
            ViewBag.topsort = CountTop;
            return View(departments);
        }
        public IActionResult Excel()
        {
            ViewBag.Parameters = _groupService.AllParameters();
            using (var workbook = new XLWorkbook())
            {
                _service.WorkbookCreate(workbook);
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(
                    content,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Top_Emplyee.xlsx");
                }
            }
        }
        public ActionResult Progress(int DepId, int Direction)
        {
            if (Direction == 1) { ViewBag.Direction = 1;}
            else {ViewBag.Direction = 0;}
            Departments departments = _service.DepEmployeesProgreses(DepId);
            ViewBag.Parameters = _groupService.AllParameters();
            ViewBag.Evaluations = _service.GetLastEvaluations();
            return View(departments);
        }
    }
}

Perfomans/Controllers/ParametersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perfomans.Models;
using Perfomans.Service;

namespace Perfomans.Controllers
{
    public class ParametersController : Controller
    {
        private readonly IParametersService _service;

        public ParametersController(IParametersService service)
        {
            _service = service;
        }
        [Authorize(Roles = "admin")]

        public IActionResult Index()
        {
            var parameters = _service.AllParameters();
            return View(parameters);
        }

        public IActionResult Details(int? id)=> View(_service.GetById(id));
        public IActionResult Create() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Coefficient,Mark_1_description,Mark_2_description,Mark_3_description,Mark_4_description,Mark_5_description")] Parameters parameters)
        {
            if (ModelState.IsValid)
            {
                _service.Insert(parameters);
                return RedirectToAction(nameof(Index));
            }
            return View(parameters);
        }
        public IActionResult Edit(int? id)=> View(_service.GetById(id));
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Coefficient,Mark_1_description,Mark_2_description,Mark_3_description,Mark_4_description,Mark_5_description")] Parameters parameters)
        {
            if (ModelState.IsValid)
            {
                _service.Update(parameters);
                return RedirectToAction(nameof(Index));
            }
            return View(parameters);
        }
        public IActionResult Delete(int? id)=> View(_service.GetById(id));

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Perfomans/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Perfomans.Models;
using Perfomans.Service;

namespace Perfomans.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _service;

        public UsersController(IUserService service)
        {
            _service = service;
        }
        [Authorize(Roles = "admin")]

        public IActionResult Index()
        {
            var users = _service.AllUsers();
            return View(users);
        }

        public IActionResult Create()
        {
            var Users = _service.AllUsers();
            var Depo = _service.AllDepartments();
            var Role = _service.AllRoles();
            var State = _service.AllStates();

            ViewData["SupervisorId"] = new SelectList(Users.ToList(), "Id", "Name", Users.ToList().Select(x => x.Id).FirstOrDefault());
            ViewData["DepartmentId"] = new SelectList(Depo.ToList(), "Id", "Name", Depo.ToList().Select(x => x.Id).FirstOrDefault());
            ViewData["RoleId"] = new SelectList(Role.ToList(), "Id", "Name", Role.ToList().Select(x => x.Id).FirstOrDefault());
            ViewData["StateId"] = new SelectList(State.ToList(), "Id", "Name", State.ToList().Select(x => x.Id).FirstOrDefault());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,SourName,Email,Password,RoleId,StateId,SupervisorId,DepartmentId")] User user)
        {
            if (ModelState.IsValid)
            {
                _service.Insert(user);
                return RedirectToAction(nameof(Index));
            }
            var Users = _service.AllUsers();
            var Depo = _service.AllDepartments();
            var Role = _service.AllRoles();
            var State = _service.AllStates();

            ViewData["DepartmentId"] = new SelectList(Depo.ToList(), "Id", "Name", user.DepartmentId);
            ViewData["RoleId"] = new SelectList(Role.ToList(), "Id", "Name", user.RoleId);
            ViewData["SupervisorId"] = new SelectList(Users.ToList(), "Id", "Name", user.SupervisorId);
            ViewData["StateId"] = new SelectList(State.ToList(), "Id", "Name", user.StateId);
            return View(user);
        }

        public IActionResult Edit(int? id)
        {
          User user = _service.GetById(id);
            var Users = _service.AllUsers();
            var Depo = _service.AllDepartments();
            var Role = _service.AllRoles();
            var State = _service.AllStates();

            ViewData["SupervisorId"] = new SelectList(Users.ToList(), "Id", "Name", Users.ToList().Select(x => x.Id).FirstOrDefault());
            ViewData["DepartmentId"] = new SelectList(Depo.ToList(), "Id", "Name", Depo.ToList().Select(x => x.Id).FirstOrDefault());
            ViewData["RoleId"] = new SelectList(Role.ToList(), "Id", "Name", Role.ToList().Select(x => x.Id).FirstOrDefault());
            ViewData["StateId"] = new SelectList(State.ToList(), "Id", "Name", State.ToList().Select(x => x.Id).FirstOrDefault());
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,SourName,Email,Password,RoleId,StateId,SupervisorId,DepartmentId")] User user)
        {
            _service.Update(user);
            var Users = _service.AllUsers();
            var Depo = _service.AllDepartments();
            var Role = _service.AllRoles();
            var State = _service.AllStates();

            ViewData["DepartmentId"] = new SelectList(Depo.ToList(), "Id", "Name", user.DepartmentId);
            ViewData["RoleId"] = new SelectList(Role.ToList(), "Id", "Name", user.RoleId);
            ViewData["SupervisorId"] = new SelectList(Users.ToList(), "Id", "Name", user.SupervisorId);
            ViewData["StateId"] = new SelectList(State.ToList(), "Id", "Name", user.StateId);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            var user = _service.GetUserNmodelsById(id);
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
           
            _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Perfomans/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] SolbegPeople</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/semantic-ui/2.2.10/semantic.min.css">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js">
    </script>
    <style>
        a {
            color: #54354F;
        }
        .PrimaryB {
            background-color: #54354F;
            color: white
        }

        .SecondaryB {
            background-color: transparent;
            color: #54354F;
            border: #54354F 0.2em solid;
            padding: 0.46em 1em;
            border-radius: 0.3em
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top" style=" background-color: #54354F; color: #ffffff">
            <div class="container">

                <a href="@Url.Action("Index", "Home", new{area = ""})" style="background-color: transparent; border: none" type="submit">
                    <img type="submit" style="margin-top: 5px;margin-left:2px; width: 160px; display:inline" src="~/WiteIcon.png" />
                </a>

                <div style="margin-top: -2.5em" class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    @if (User.Identity.IsAuthenticated)
                    {

                        using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()

                            <ul style="display:inline; color: white" class="nav navbar-nav navbar-right">
                                <li style="display:inline; margin-right: 1em">
                                    Hello,@User.Identity.Name!
                                </li>
                                <li class="nav-item" style="display:inline">
                                    <form class="form-inline" asp-area="Identity" asp-page="/Users/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button type="submit" class="nav-link btn btn-link ui inverted button">Logout</button>
                                    </form>
                                </li>
                            </ul>
                            <ul style="display:inline; color: white; margin-right: 20%" class="nav navbar-nav">
                                <li style="display:inline; color: white">
                                    <a style="display:inline; color: white; padding-right: 2em" class="nav-link btn btn-link" asp-area="" asp-controller="Parameters" asp-action="Index">Parameters</a>
                                </li>
                                <li style="display:inline; color: white">
                                    <a style="display:inline; color: white;padding-right: 2em" class="nav-link btn btn-link" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                                </li>
                                <li style="display:inline; color: white">
                                    <a style="display:inline; color: white;padding-right: 2em"  class="nav-link btn btn-link" asp-area="" asp-controller="Users" asp-action="Index">Employees</a>
                                </li>
                                <li style="display:inline; color: white">
                                    <a style="display:inline; color: white" class="nav-link btn btn-link" asp-area="" asp-controller="Chart" asp-action="Index">Hierarchy</a>
                                </li>
                            </ul>
                        }
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>